import React, { useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { Plus, Video, Search, Grid3X3, List, RefreshCw } from 'lucide-react';

interface Project { id:string; name:string; createdAt:string; updatedAt:string; }

export function DashboardPage(){
  const [projects,setProjects]=useState<Project[]>([]); const [search,setSearch]=useState(''); const [view,setView]=useState<'grid'|'list'>('grid'); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [userName,setUserName]=useState('Creator'); const navigate=useNavigate();
  async function load(){setLoading(true);setError('');try{const r=await fetch('/api/projects');if(!r.ok)throw new Error('تعذر تحميل المشاريع');setProjects(await r.json());}catch(e){setError(e instanceof Error?e.message:'تعذر تحميل المشاريع');}finally{setLoading(false);}}
  useEffect(()=>{void load();supabase.auth.getUser().then(({data})=>{if(data.user?.user_metadata?.name)setUserName(data.user.user_metadata.name);});},[]);
  const filtered=useMemo(()=>projects.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())),[projects,search]);
  async function signOut(){await supabase.auth.signOut();navigate('/auth');}
  async function create(){const r=await fetch('/api/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'مشروع فيديو جديد'})});if(r.ok){const p=await r.json();navigate(`/project/${p.id}`);}else setError('تعذر إنشاء المشروع');}
  return <div className="h-screen w-screen bg-[#0a0a0f] overflow-y-auto text-white">
    <header className="sticky top-0 z-50 bg-surface/90 backdrop-blur-lg border-b border-border"><div className="max-w-6xl mx-auto px-5 py-4 flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary-500 to-accent-cyan flex items-center justify-center font-bold">AI</div><div><div className="font-semibold">AI Creative Studio</div><div className="text-xs text-white/40">Integrated Video MVP</div></div></div><div className="flex items-center gap-2"><button className="btn" onClick={()=>void load()} title="تحديث"><RefreshCw className="w-4 h-4"/></button><button className="text-sm text-white/60 hover:text-white" onClick={()=>void signOut()}>خروج</button></div></div></header>
    <main className="max-w-6xl mx-auto px-5 py-8"><div className="flex items-end justify-between gap-4 mb-8 flex-wrap"><div><h1 className="text-2xl font-bold">مرحبًا {userName}</h1><p className="text-white/50 mt-1">أنشئ مشروع فيديو وابدأ التحرير مباشرة.</p></div><button className="btn btn-primary btn-lg" onClick={()=>void create()}><Plus className="w-5 h-5"/>مشروع جديد</button></div>
      <div className="flex items-center gap-3 mb-6"><div className="relative flex-1 max-w-xl"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-white/30"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="البحث في المشاريع" className="w-full bg-surface-elevated border border-border rounded-lg pl-10 pr-3 py-2 text-sm"/></div><button className="btn" onClick={()=>setView(v=>v==='grid'?'list':'grid')}>{view==='grid'?<List className="w-4 h-4"/>:<Grid3X3 className="w-4 h-4"/>}</button></div>
      {error&&<div className="mb-5 rounded-lg border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">{error}</div>}
      {loading?<div className="py-20 text-center text-white/40">جاري تحميل المشاريع…</div>:filtered.length===0?<div className="py-20 text-center rounded-xl border border-dashed border-border"><Video className="w-10 h-10 mx-auto text-white/20"/><p className="mt-3 text-white/50">لا توجد مشاريع بعد.</p><button className="btn btn-primary mt-4" onClick={()=>void create()}>أنشئ أول مشروع</button></div>:(view==='grid'?<div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">{filtered.map(p=><Link key={p.id} to={`/project/${p.id}`} className="group bg-surface-elevated border border-border rounded-xl overflow-hidden hover:border-primary-500 transition"><div className="aspect-video bg-[#05070a] flex items-center justify-center"><Video className="w-12 h-12 text-white/20 group-hover:text-primary-400 transition"/></div><div className="p-4"><div className="font-medium truncate">{p.name}</div><div className="text-xs text-white/40 mt-1">{new Date(p.updatedAt).toLocaleString()}</div></div></Link>)}</div>:<div className="rounded-xl overflow-hidden border border-border bg-surface-elevated">{filtered.map((p,i)=><Link key={p.id} to={`/project/${p.id}`} className={`flex items-center gap-3 px-4 py-3 hover:bg-white/5 ${i?'border-t border-border':''}`}><Video className="w-5 h-5 text-primary-400"/><span className="flex-1 truncate">{p.name}</span><span className="text-xs text-white/40">{new Date(p.updatedAt).toLocaleString()}</span></Link>)}</div>)}
    </main>
  </div>;
}
